stages:
  - PesterTest
  - BuildModule
  - ScriptAnalyzerTest
  - CreateNugetPackage
  - DeployGitlabPackage
  - DeployProgetPackages
  - DeployChocolateyPackage
  - DeployPsgallaryPackage
  - DeployCoverageToCoverails
  - CreateRelease

# Pester Test Stage
pester_test_job:
  stage: PesterTest
  tags:
    - win64
    - linux-x64
  script:
    - pwsh
    - install-module -name pester -Scope CurrentUser -Force -SkipPublisherCheck
    - import-module -name pester -Force
    - invoke-Pester -Script .\bt0-ci-test-pester.ps1

# Build Module Stage
build_module_job:
  stage: BuildModule
  tags:
    - win64
    - linux-x64
  script:
    - pwsh
    - Test-ModuleManifest -Path ./dist/commitfusion/commitfusion.psd1
    - ./bt1-ci-build-module.ps1
  artifacts:
    paths:
    - ./dist/commiffusion

# Script Analyzer Test Stage
script_analyzer_test_job:
  stage: ScriptAnalyzerTest
  tags:
    - win64
    - linux-x64
  rules:
    - if: '$CI_BUILD_STAGE == "BuildModule" && $CI_BUILD_STATUS == "success"'
  script:
    - pwsh
    - install-module -name PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck
    - import-module -name PSScriptAnalyzer -Force
    - .\bt1-p2-ci-test-pssa.ps1
  artifacts:
    paths:
    - ./dist/commitfusion

# Create Nuget Package Stage
create_nuget_package_job:
  stage: CreateNugetPackage
  tags:
    - win64
    - linux-x64
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "ScriptAnalyzerTest" && $CI_BUILD_STATUS == "success"'
  script:
    - pwsh.exe
    - .\bt2-ci-create-packages.ps1
  artifacts:
    paths:
    - ./dist/commitfusion
    - ./dist/choco
    - ./dist/psgal
    - ./dist/nuget

# Deploy GitLab Package Stage
deploy_gitlab_package_job:
  stage: DeployGitlabPackage
  tags:
    - win64
    - linux-x64
  script:
    - pwsh.exe
    - .\bt3-ci-deploy-pushtogitlab.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "CreateNugetPackage" && $CI_BUILD_STATUS == "success"'

# Deploy Proget Packages Stage
deploy_proget_packages_job:
  stage: DeployProgetPackages
  tags:
    - win64
    - linux-x64
  script:
    - pwsh.exe
    - .\bt4-ci-deploy-pushtoproget.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "DeployGitlabPackage" && $CI_BUILD_STATUS == "success"'

# Deploy Chocolatey Package Stage
deploy_chocolatey_package_job:
  stage: DeployChocolateyPackage
  tags:
    - win64
    - linux-x64
  script:
    - pwsh.exe
    - .\BT5-CI-deploy-PushToChoco.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "DeployProgetPackages" && $CI_BUILD_STATUS == "success"'

# Deploy PSGallary Package Stage
deploy_psgallary_package_job:
  stage: DeployPsgallaryPackage
  tags:
    - win64
    - linux-x64
  script:
    - pwsh.exe
    - .\bt6-ci-deploy-psgallary.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "DeployChocolateyPackage" && $CI_BUILD_STATUS == "success"'

# Deploy Coverage to Coverails.io Stage
deploy_coverage_coverails_job:
  stage: DeployCoverageToCoverails
  tags:
    - win64
    - linux-x64
  script:
    - pwsh.exe
    - .\bt8-ci-deploy-coveralls-report.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "DeployPsgallaryPackage" && $CI_BUILD_STATUS == "success"'

# Create Release Stage
create_release_job:
  stage: CreateRelease
  script: 
    - pwsh.exe
    - Compress-Archive -Path .\ -DestinationPath Build.gz
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "DeployPsgallaryPackage" && $CI_BUILD_STATUS == "success"'
  artifacts:
    paths:
      - Build.gz
