# author: mnoxx @ proton me
# date: Saturday, 24 September 2022 2:24:20 AM
# version: v1.1
# env: powershell(5.x), pwsh(7.x)
stages:
  - Build-Module # Copy Module files for build
  - Test-Module # Testing Module againsts predefined scripts
  - Test-PSM # Test .psd1 profile
  - Test-PSA # Run Module files through PSScriptAnalyzer
  - Create-Nuget-Package # Create nupkg Package from build
  - Deploy-Gitlab-Package # Deploy Package to gitlab nuget
  - Deploy-Proget-Packages # Deploy Package to Proget[nuget,psgallary,chocolatey] feeds 
  - Deploy-PSGallary-Package # Deploy Package to PSGallary
  - Deploy-Chocolatey # Deploy Package to Chocolatey
  - Deploy-Coverage-Coverails # Deploy Coverage to Coverails.io
  - Create-Release # Create Release
build-job:
  stage: build
  tags:
    - windows
    - pwsh-core
  script:
    - pwsh
    - Test-ModuleManifest -Path ./disk/commitfusion/commitfusion.psd1
    - ./CI-Build-Module.ps1
  artifacts:
    paths:
    - ./dist/commiffusion
#    expire_in: 20 minutes

Test-ScriptAnalyzer-job:
  stage: Test-PSM
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "Build-Module" && $CI_BUILD_STATUS == "success"'
  script:
    - pwsh
    - install-module -name PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck
    - import-module -name PSScriptAnalyzer -Force
    - Invoke-ScriptAnalyzer -Path ./dist/commitfusion/*.ps1
    - Invoke-ScriptAnalyzer -Path ./dist/commitfusion/*.psm1
  artifacts:
    paths:
    - ./dist/commitfusion
#    expire_in: 20 minutes

Test-Pester-job:
  stage: Test-PSA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "Test-PSM" && $CI_BUILD_STATUS == "success"'
  script:
    - pwsh
    - install-module -name pester -Scope CurrentUser -Force -SkipPublisherCheck
    - import-module -name pester -Force
  artifacts:
    paths:
    - ./dist/commitfusion
#    expire_in: 20 minutes

Create-Nuget-Package-job:
  stage: Create-Nuget-Package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "Test-PSA" && $CI_BUILD_STATUS == "success"'
  script:
    - pwsh.exe
    - .\ci-build-nupkg.ps1
  artifacts:
    paths:
    - ./dist/commitfusion
    - ./dist/choco
    - ./dist/psgal
    - ./dist/nuget
#    expire_in: 20 minutes

Deploy-Gitlab-Package-job:
  stage: Deploy-Gitlab-Package
  script:
    - pwsh.exe
    - .\CI-Build-PushToGitlab.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'
    
deploy-nugetgitlab-job:
  stage: deploy_nugetgitlab
  script:
    - pwsh.exe
    - .\CI-Send-PushToGitlab.ps1
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'

manual-deploy-psgallary-job:
  stage: manual_deploy_psgallary
  when: manual
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploy_nugetgitlab" && $CI_BUILD_STATUS == "success"'
# Release a Package
package:
  script: Compress-Archive -Path .\Build -DestinationPath Build.gz
  artifacts:
    paths:
    - Build.gz