repository: pages-themes/slate
#author: # [name, email, web]
remote_theme: pages-themes/slate@v0.2.0
title: [Commit-Fusion] # Used Front Matter property
description: [Conventional Commit Message Generator] # Used Front Matter property
show_downloads: true  # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-gist
kramdown:
  input: GFM
  syntax_highlighter: rouge
defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false