repository: sgkens/slate-fusion
#author: # [name, email, web]
remote_theme: pages-themes/slate@v0.2.0
title: [CommitFusion] 
description: [Conventional Commit Message Generator]
show_downloads: true  # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
custom:
  logo:         'https://raw.githubusercontent.com/sgkens/resources/main/modules/CommitFusion/dist/v2/logo-black-v2.svg' 
  dateupdated:  'Tuesday, 28 November 2023 8:26:40 PM' 
  license:      'https://img.shields.io/badge/MIT-License-blue?style=flat&logo=unlicense&color=#36013f' 
  version:      'https://img.shields.io/badge/version-v0.3.1-blue?style=flat&logo=Version&color=%23004481'
  choco:        'https://img.shields.io/chocolatey/dt/commitfusion?style=flat&logo=Chocolatey&labelColor=darkmagenta&color=gray'
  psgallary:    'https://img.shields.io/powershellgallery/dt/commitfusion?style=flat&logo=powershell&labelColor=blue&color=gray'

  
#google_analytics: [Your Google Analytics tracking ID]
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-gist
kramdown:
  input: GFM
  syntax_highlighter: rouge
defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false